version: "3"
services:
  kademliaNodes:
    image: test/dfs:latest
    stdin_open: true
    tty: true
    environment:
      BOOTSTRAP_ADDR: "bootstrapingNode:44135"
      LISTEN_PORT: ":44135"
      FILE_TRANSFER_PORT: ":44589"
      REPUBLISH_TIME:  30 #3600
      ORG_REPUBLISH_TIME: 50  #86400
      EXPARATION_TIME: 40 #86410
    depends_on:
      - "bootstrapingNode"
      - "kademlia_network"
    deploy:
      replicas: 30
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
    - kademlia_network

  bootstrapingNode:
    image: test/dfs:latest
    stdin_open: true
    tty: true
    environment:
      LISTEN_PORT: ":44135"
      FILE_TRANSFER_PORT: ":44589"
      REPUBLISH_TIME:  60 #3600
      ORG_REPUBLISH_TIME: 40  #86400
      EXPARATION_TIME: 30 #86410
    depends_on:
      - "kademlia_network"
    deploy:

      replicas: 1
      #        resources:
      #           limits:
      #              cpus: "0.1"
      #              memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - kademlia_network

  testNode:
    image: larjim/kademlialab:latest
    stdin_open: true
    tty: true
    environment:
      BOOTSTRAP_ADDR: "bootstrapingNode:44135"
      LISTEN_PORT: ":44135"
      FILE_TRANSFER_PORT: ":44589"
    depends_on:
      - "kademlia_network"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - kademlia_network

networks:
  kademlia_network:
    ipam:
      driver: default
      config:
        - subnet: 10.4.0.0/16