// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Protocol files/FIND_NODE.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindNode struct {
	Contacts             []*FindNode_Contact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	TargetID             []byte              `protobuf:"bytes,2,opt,name=targetID,proto3" json:"targetID,omitempty"`
	KademliaID           []byte              `protobuf:"bytes,3,opt,name=KademliaID,proto3" json:"KademliaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FindNode) Reset()         { *m = FindNode{} }
func (m *FindNode) String() string { return proto.CompactTextString(m) }
func (*FindNode) ProtoMessage()    {}
func (*FindNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c6db2d5f89330, []int{0}
}

func (m *FindNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNode.Unmarshal(m, b)
}
func (m *FindNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNode.Marshal(b, m, deterministic)
}
func (m *FindNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNode.Merge(m, src)
}
func (m *FindNode) XXX_Size() int {
	return xxx_messageInfo_FindNode.Size(m)
}
func (m *FindNode) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNode.DiscardUnknown(m)
}

var xxx_messageInfo_FindNode proto.InternalMessageInfo

func (m *FindNode) GetContacts() []*FindNode_Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *FindNode) GetTargetID() []byte {
	if m != nil {
		return m.TargetID
	}
	return nil
}

func (m *FindNode) GetKademliaID() []byte {
	if m != nil {
		return m.KademliaID
	}
	return nil
}

type FindNode_Contact struct {
	IPaddress            string   `protobuf:"bytes,1,opt,name=IPaddress,proto3" json:"IPaddress,omitempty"`
	KademliaID           []byte   `protobuf:"bytes,2,opt,name=kademliaID,proto3" json:"kademliaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindNode_Contact) Reset()         { *m = FindNode_Contact{} }
func (m *FindNode_Contact) String() string { return proto.CompactTextString(m) }
func (*FindNode_Contact) ProtoMessage()    {}
func (*FindNode_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_413c6db2d5f89330, []int{0, 0}
}

func (m *FindNode_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindNode_Contact.Unmarshal(m, b)
}
func (m *FindNode_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindNode_Contact.Marshal(b, m, deterministic)
}
func (m *FindNode_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindNode_Contact.Merge(m, src)
}
func (m *FindNode_Contact) XXX_Size() int {
	return xxx_messageInfo_FindNode_Contact.Size(m)
}
func (m *FindNode_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_FindNode_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_FindNode_Contact proto.InternalMessageInfo

func (m *FindNode_Contact) GetIPaddress() string {
	if m != nil {
		return m.IPaddress
	}
	return ""
}

func (m *FindNode_Contact) GetKademliaID() []byte {
	if m != nil {
		return m.KademliaID
	}
	return nil
}

func init() {
	proto.RegisterType((*FindNode)(nil), "protocol.FindNode")
	proto.RegisterType((*FindNode_Contact)(nil), "protocol.FindNode.Contact")
}

func init() { proto.RegisterFile("Protocol files/FIND_NODE.proto", fileDescriptor_413c6db2d5f89330) }

var fileDescriptor_413c6db2d5f89330 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0x51, 0x48, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0x77, 0xf3, 0xf4, 0x73, 0x89,
	0xf7, 0xf3, 0x77, 0x71, 0xd5, 0x2b, 0x00, 0x49, 0x08, 0x71, 0x14, 0x40, 0xe5, 0x95, 0x8e, 0x33,
	0x72, 0x71, 0xb8, 0x65, 0xe6, 0xa5, 0xf8, 0xe5, 0xa7, 0xa4, 0x0a, 0x99, 0x71, 0x71, 0x24, 0xe7,
	0xe7, 0x95, 0x24, 0x26, 0x97, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x49, 0xe9, 0xc1,
	0x54, 0xea, 0xc1, 0x54, 0xe9, 0x39, 0x43, 0x94, 0x04, 0xc1, 0xd5, 0x0a, 0x49, 0x71, 0x71, 0x94,
	0x24, 0x16, 0xa5, 0xa7, 0x96, 0x78, 0xba, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0xc1, 0xf9,
	0x42, 0x72, 0x5c, 0x5c, 0xde, 0x89, 0x29, 0xa9, 0xb9, 0x39, 0x99, 0x89, 0x9e, 0x2e, 0x12, 0xcc,
	0x60, 0x59, 0x24, 0x11, 0x29, 0x77, 0x2e, 0x76, 0xa8, 0x81, 0x42, 0x32, 0x5c, 0x9c, 0x9e, 0x01,
	0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0x20, 0xfb, 0x19, 0x35, 0x38, 0x83, 0x10, 0x02, 0x20, 0x83,
	0xb2, 0x11, 0x06, 0x41, 0xac, 0x41, 0x12, 0x49, 0x62, 0x03, 0xbb, 0xd4, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x1f, 0x63, 0xa1, 0x57, 0xfc, 0x00, 0x00, 0x00,
}
