// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FIND_VALUE.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindValue struct {
	Contacts             []*FindValue_Contact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	TargetID             []byte               `protobuf:"bytes,2,opt,name=targetID,proto3" json:"targetID,omitempty"`
	Password             []byte               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FileHash             []byte               `protobuf:"bytes,4,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindValue) Reset()         { *m = FindValue{} }
func (m *FindValue) String() string { return proto.CompactTextString(m) }
func (*FindValue) ProtoMessage()    {}
func (*FindValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_627a9be656976796, []int{0}
}

func (m *FindValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValue.Unmarshal(m, b)
}
func (m *FindValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValue.Marshal(b, m, deterministic)
}
func (m *FindValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValue.Merge(m, src)
}
func (m *FindValue) XXX_Size() int {
	return xxx_messageInfo_FindValue.Size(m)
}
func (m *FindValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValue.DiscardUnknown(m)
}

var xxx_messageInfo_FindValue proto.InternalMessageInfo

func (m *FindValue) GetContacts() []*FindValue_Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *FindValue) GetTargetID() []byte {
	if m != nil {
		return m.TargetID
	}
	return nil
}

func (m *FindValue) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *FindValue) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

type FindValue_Contact struct {
	IPaddress            string   `protobuf:"bytes,1,opt,name=IPaddress,proto3" json:"IPaddress,omitempty"`
	KademliaID           []byte   `protobuf:"bytes,2,opt,name=kademliaID,proto3" json:"kademliaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindValue_Contact) Reset()         { *m = FindValue_Contact{} }
func (m *FindValue_Contact) String() string { return proto.CompactTextString(m) }
func (*FindValue_Contact) ProtoMessage()    {}
func (*FindValue_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_627a9be656976796, []int{0, 0}
}

func (m *FindValue_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValue_Contact.Unmarshal(m, b)
}
func (m *FindValue_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValue_Contact.Marshal(b, m, deterministic)
}
func (m *FindValue_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValue_Contact.Merge(m, src)
}
func (m *FindValue_Contact) XXX_Size() int {
	return xxx_messageInfo_FindValue_Contact.Size(m)
}
func (m *FindValue_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValue_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_FindValue_Contact proto.InternalMessageInfo

func (m *FindValue_Contact) GetIPaddress() string {
	if m != nil {
		return m.IPaddress
	}
	return ""
}

func (m *FindValue_Contact) GetKademliaID() []byte {
	if m != nil {
		return m.KademliaID
	}
	return nil
}

func init() {
	proto.RegisterType((*FindValue)(nil), "protocol.FindValue")
	proto.RegisterType((*FindValue_Contact)(nil), "protocol.FindValue.Contact")
}

func init() { proto.RegisterFile("FIND_VALUE.proto", fileDescriptor_627a9be656976796) }

var fileDescriptor_627a9be656976796 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x70, 0xf3, 0xf4, 0x73,
	0x89, 0x0f, 0x73, 0xf4, 0x09, 0x75, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0xc9, 0xf9, 0x39, 0x4a, 0x0f, 0x19, 0xb9, 0x38, 0xdd, 0x32, 0xf3, 0x52, 0xc2, 0x12, 0x73, 0x4a,
	0x53, 0x85, 0xcc, 0xb9, 0x38, 0x92, 0xf3, 0xf3, 0x4a, 0x12, 0x93, 0x4b, 0x8a, 0x25, 0x18, 0x15,
	0x98, 0x35, 0xb8, 0x8d, 0xa4, 0xf5, 0x60, 0x4a, 0xf5, 0xe0, 0xca, 0xf4, 0x9c, 0x21, 0x6a, 0x82,
	0xe0, 0x8a, 0x85, 0xa4, 0xb8, 0x38, 0x4a, 0x12, 0x8b, 0xd2, 0x53, 0x4b, 0x3c, 0x5d, 0x24, 0x98,
	0x14, 0x18, 0x35, 0x78, 0x82, 0xe0, 0x7c, 0x90, 0x5c, 0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51,
	0x8a, 0x04, 0x33, 0x44, 0x0e, 0xc6, 0x07, 0xc9, 0xa5, 0x65, 0xe6, 0xa4, 0x7a, 0x24, 0x16, 0x67,
	0x48, 0xb0, 0x40, 0xe4, 0x60, 0x7c, 0x29, 0x77, 0x2e, 0x76, 0xa8, 0x45, 0x42, 0x32, 0x5c, 0x9c,
	0x9e, 0x01, 0x89, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0x20, 0x87, 0x31, 0x6a, 0x70, 0x06, 0x21, 0x04,
	0x84, 0xe4, 0xb8, 0xb8, 0xb2, 0x13, 0x53, 0x52, 0x73, 0x73, 0x32, 0x13, 0xe1, 0xd6, 0x23, 0x89,
	0x24, 0xb1, 0x81, 0xbd, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x40, 0xf7, 0x3b, 0x6a, 0x08,
	0x01, 0x00, 0x00,
}
