// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Protocol files/FIND_VALUE.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindValue struct {
	Contacts             []*FindValue_Contact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	FileHash             []byte               `protobuf:"bytes,2,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	HaveTheFile          bool                 `protobuf:"varint,3,opt,name=HaveTheFile,proto3" json:"HaveTheFile,omitempty"`
	FileName             string               `protobuf:"bytes,4,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize             int64                `protobuf:"varint,5,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindValue) Reset()         { *m = FindValue{} }
func (m *FindValue) String() string { return proto.CompactTextString(m) }
func (*FindValue) ProtoMessage()    {}
func (*FindValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1461852405a15972, []int{0}
}

func (m *FindValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValue.Unmarshal(m, b)
}
func (m *FindValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValue.Marshal(b, m, deterministic)
}
func (m *FindValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValue.Merge(m, src)
}
func (m *FindValue) XXX_Size() int {
	return xxx_messageInfo_FindValue.Size(m)
}
func (m *FindValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValue.DiscardUnknown(m)
}

var xxx_messageInfo_FindValue proto.InternalMessageInfo

func (m *FindValue) GetContacts() []*FindValue_Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

func (m *FindValue) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *FindValue) GetHaveTheFile() bool {
	if m != nil {
		return m.HaveTheFile
	}
	return false
}

func (m *FindValue) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FindValue) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type FindValue_Contact struct {
	IPaddress            string   `protobuf:"bytes,1,opt,name=IPaddress,proto3" json:"IPaddress,omitempty"`
	KademliaID           []byte   `protobuf:"bytes,2,opt,name=kademliaID,proto3" json:"kademliaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindValue_Contact) Reset()         { *m = FindValue_Contact{} }
func (m *FindValue_Contact) String() string { return proto.CompactTextString(m) }
func (*FindValue_Contact) ProtoMessage()    {}
func (*FindValue_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_1461852405a15972, []int{0, 0}
}

func (m *FindValue_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindValue_Contact.Unmarshal(m, b)
}
func (m *FindValue_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindValue_Contact.Marshal(b, m, deterministic)
}
func (m *FindValue_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindValue_Contact.Merge(m, src)
}
func (m *FindValue_Contact) XXX_Size() int {
	return xxx_messageInfo_FindValue_Contact.Size(m)
}
func (m *FindValue_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_FindValue_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_FindValue_Contact proto.InternalMessageInfo

func (m *FindValue_Contact) GetIPaddress() string {
	if m != nil {
		return m.IPaddress
	}
	return ""
}

func (m *FindValue_Contact) GetKademliaID() []byte {
	if m != nil {
		return m.KademliaID
	}
	return nil
}

func init() {
	proto.RegisterType((*FindValue)(nil), "protocol.FindValue")
	proto.RegisterType((*FindValue_Contact)(nil), "protocol.FindValue.Contact")
}

func init() { proto.RegisterFile("Protocol files/FIND_VALUE.proto", fileDescriptor_1461852405a15972) }

var fileDescriptor_1461852405a15972 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0x51, 0x48, 0xcb, 0xcc, 0x49, 0x2d, 0xd6, 0x77, 0xf3, 0xf4, 0x73, 0x89,
	0x0f, 0x73, 0xf4, 0x09, 0x75, 0xd5, 0x2b, 0x00, 0xc9, 0x08, 0x71, 0x14, 0x40, 0x15, 0x28, 0x35,
	0x33, 0x71, 0x71, 0xba, 0x65, 0xe6, 0xa5, 0x84, 0x25, 0xe6, 0x94, 0xa6, 0x0a, 0x99, 0x73, 0x71,
	0x24, 0xe7, 0xe7, 0x95, 0x24, 0x26, 0x97, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x49,
	0xeb, 0xc1, 0x94, 0xea, 0xc1, 0x95, 0xe9, 0x39, 0x43, 0xd4, 0x04, 0xc1, 0x15, 0x0b, 0x49, 0x71,
	0x71, 0x80, 0xac, 0xf2, 0x48, 0x2c, 0xce, 0x90, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0xf3,
	0x85, 0x14, 0xb8, 0xb8, 0x3d, 0x12, 0xcb, 0x52, 0x43, 0x32, 0x52, 0xdd, 0x32, 0x73, 0x52, 0x25,
	0x98, 0x15, 0x18, 0x35, 0x38, 0x82, 0x90, 0x85, 0x60, 0xba, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x58,
	0x14, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x98, 0x5c, 0x70, 0x66, 0x55, 0xaa, 0x04, 0xab, 0x02,
	0xa3, 0x06, 0x73, 0x10, 0x9c, 0x2f, 0xe5, 0xce, 0xc5, 0x0e, 0x75, 0x8a, 0x90, 0x0c, 0x17, 0xa7,
	0x67, 0x40, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x31, 0xc8, 0xe9, 0x20, 0x33, 0x10, 0x02, 0x42, 0x72,
	0x5c, 0x5c, 0xd9, 0x89, 0x29, 0xa9, 0xb9, 0x39, 0x99, 0x89, 0x9e, 0x2e, 0x50, 0x07, 0x22, 0x89,
	0x24, 0xb1, 0x81, 0x3d, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x85, 0xc4, 0x3a, 0xce, 0x39,
	0x01, 0x00, 0x00,
}
