// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PING.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ping struct {
	KademliaID           []byte   `protobuf:"bytes,1,opt,name=KademliaID,proto3" json:"KademliaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b38ee85b5f89f92, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetKademliaID() []byte {
	if m != nil {
		return m.KademliaID
	}
	return nil
}

func init() {
	proto.RegisterType((*Ping)(nil), "protocol.Ping")
}

func init() { proto.RegisterFile("PING.proto", fileDescriptor_8b38ee85b5f89f92) }

var fileDescriptor_8b38ee85b5f89f92 = []byte{
	// 79 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0a, 0xf0, 0xf4, 0x73,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x6a, 0x5c,
	0x2c, 0x01, 0x99, 0x79, 0xe9, 0x42, 0x72, 0x5c, 0x5c, 0xde, 0x89, 0x29, 0xa9, 0xb9, 0x39, 0x99,
	0x89, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x48, 0x22, 0x49, 0x6c, 0x60, 0x1d,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0x76, 0x92, 0xdf, 0x46, 0x00, 0x00, 0x00,
}
