// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RPC.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Specifies the message type contained in message
type RPCMessageTYPE int32

const (
	RPC_PING       RPCMessageTYPE = 0
	RPC_STORE      RPCMessageTYPE = 1
	RPC_FIND_NODE  RPCMessageTYPE = 2
	RPC_FIND_VALUE RPCMessageTYPE = 3
	RPC_PIN        RPCMessageTYPE = 4
	RPC_UNPIN      RPCMessageTYPE = 5
)

var RPCMessageTYPE_name = map[int32]string{
	0: "PING",
	1: "STORE",
	2: "FIND_NODE",
	3: "FIND_VALUE",
	4: "PIN",
	5: "UNPIN",
}

var RPCMessageTYPE_value = map[string]int32{
	"PING":       0,
	"STORE":      1,
	"FIND_NODE":  2,
	"FIND_VALUE": 3,
	"PIN":        4,
	"UNPIN":      5,
}

func (x RPCMessageTYPE) String() string {
	return proto.EnumName(RPCMessageTYPE_name, int32(x))
}

func (RPCMessageTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_438fa73ead152342, []int{0, 0}
}

type RPC struct {
	// Unique 160-bit message ID used for routing purposes
	MessageID   []byte         `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	MessageType RPCMessageTYPE `protobuf:"varint,2,opt,name=messageType,proto3,enum=protocol.RPCMessageTYPE" json:"messageType,omitempty"`
	// Contains the serialized message
	Message              []byte   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	IPaddress            string   `protobuf:"bytes,4,opt,name=IPaddress,proto3" json:"IPaddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_438fa73ead152342, []int{0}
}

func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (m *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(m, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

func (m *RPC) GetMessageType() RPCMessageTYPE {
	if m != nil {
		return m.MessageType
	}
	return RPC_PING
}

func (m *RPC) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RPC) GetIPaddress() string {
	if m != nil {
		return m.IPaddress
	}
	return ""
}

func init() {
	proto.RegisterType((*RPC)(nil), "protocol.RPC")
	proto.RegisterEnum("protocol.RPCMessageTYPE", RPCMessageTYPE_name, RPCMessageTYPE_value)
}

func init() { proto.RegisterFile("RPC.proto", fileDescriptor_438fa73ead152342) }

var fileDescriptor_438fa73ead152342 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0c, 0x0a, 0x70, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xef, 0x19, 0xb9,
	0x98, 0x83, 0x02, 0x9c, 0x85, 0x64, 0xb8, 0x38, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x3d,
	0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x10, 0x02, 0x42, 0xd6, 0x5c, 0xdc, 0x50, 0x4e,
	0x48, 0x65, 0x41, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0xa4, 0x1e, 0xcc, 0x14, 0x3d,
	0x90, 0xc9, 0x30, 0x05, 0x91, 0x01, 0xae, 0x41, 0xc8, 0xaa, 0x85, 0x24, 0xb8, 0xd8, 0xa1, 0x5c,
	0x09, 0x66, 0xb0, 0xc1, 0x30, 0x2e, 0xc8, 0x52, 0xcf, 0x80, 0xc4, 0x94, 0x94, 0xa2, 0xd4, 0xe2,
	0x62, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x52, 0x28, 0xc2, 0xd2, 0xc8, 0x00,
	0x57, 0x21, 0x0e, 0x2e, 0x96, 0x00, 0x4f, 0x3f, 0x77, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0xd6, 0xe0,
	0x10, 0xff, 0x20, 0x57, 0x01, 0x46, 0x21, 0x5e, 0x2e, 0x4e, 0x37, 0x4f, 0x3f, 0x97, 0x78, 0x3f,
	0x7f, 0x17, 0x57, 0x01, 0x26, 0x21, 0x3e, 0x2e, 0x2e, 0x30, 0x37, 0xcc, 0xd1, 0x27, 0xd4, 0x55,
	0x80, 0x59, 0x88, 0x9d, 0x8b, 0x39, 0xc0, 0xd3, 0x4f, 0x80, 0x05, 0xa4, 0x25, 0xd4, 0x0f, 0xc4,
	0x64, 0x4d, 0x62, 0x03, 0xbb, 0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xec, 0x61, 0xd9, 0x9d,
	0x0f, 0x01, 0x00, 0x00,
}
