// Code generated by protoc-gen-go. DO NOT EDIT.
// source: STORE.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Store struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileSize             int64    `protobuf:"varint,2,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e165b2134302cd, []int{0}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Store) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Store)(nil), "protocol.Store")
}

func init() { proto.RegisterFile("STORE.proto", fileDescriptor_93e165b2134302cd) }

var fileDescriptor_93e165b2134302cd = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0e, 0x0e, 0xf1, 0x0f,
	0x72, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xf6,
	0x5c, 0xac, 0xc1, 0x25, 0xf9, 0x45, 0xa9, 0x42, 0x52, 0x5c, 0x1c, 0x69, 0x99, 0x39, 0xa9, 0x79,
	0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x4c, 0x2e, 0x38, 0xb3,
	0x2a, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x39, 0x08, 0xce, 0x4f, 0x62, 0x03, 0x1b, 0x65, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x4c, 0x16, 0x75, 0x60, 0x00, 0x00, 0x00,
}
