// Code generated by protoc-gen-go. DO NOT EDIT.
// source: STORE.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Store struct {
	FileHash             []byte   `protobuf:"bytes,1,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	File                 []byte   `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	Password             []byte   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_93e165b2134302cd, []int{0}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetFileHash() []byte {
	if m != nil {
		return m.FileHash
	}
	return nil
}

func (m *Store) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *Store) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func init() {
	proto.RegisterType((*Store)(nil), "protocol.Store")
}

func init() { proto.RegisterFile("STORE.proto", fileDescriptor_93e165b2134302cd) }

var fileDescriptor_93e165b2134302cd = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0e, 0x0e, 0xf1, 0x0f,
	0x72, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xc1,
	0x5c, 0xac, 0xc1, 0x25, 0xf9, 0x45, 0xa9, 0x42, 0x52, 0x5c, 0x1c, 0x69, 0x99, 0x39, 0xa9, 0x1e,
	0x89, 0xc5, 0x19, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x70, 0xbe, 0x90, 0x10, 0x17, 0x8b,
	0x5b, 0x66, 0x4e, 0xaa, 0x04, 0x13, 0x58, 0x1c, 0xcc, 0x06, 0xa9, 0x2f, 0x48, 0x2c, 0x2e, 0x2e,
	0xcf, 0x2f, 0x4a, 0x91, 0x60, 0x86, 0xa8, 0x87, 0xf1, 0x93, 0xd8, 0xc0, 0xc6, 0x1b, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x8d, 0xb2, 0xf5, 0x2e, 0x74, 0x00, 0x00, 0x00,
}
