// Code generated by protoc-gen-go. DO NOT EDIT.
// source: STORE_ANSWER.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreAnswerStoreAnswer int32

const (
	StoreAnswer_OK             StoreAnswerStoreAnswer = 0
	StoreAnswer_ALREADY_STORED StoreAnswerStoreAnswer = 1
	StoreAnswer_ERROR          StoreAnswerStoreAnswer = 2
)

var StoreAnswerStoreAnswer_name = map[int32]string{
	0: "OK",
	1: "ALREADY_STORED",
	2: "ERROR",
}

var StoreAnswerStoreAnswer_value = map[string]int32{
	"OK":             0,
	"ALREADY_STORED": 1,
	"ERROR":          2,
}

func (x StoreAnswerStoreAnswer) String() string {
	return proto.EnumName(StoreAnswerStoreAnswer_name, int32(x))
}

func (StoreAnswerStoreAnswer) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a33ff9908270bf1e, []int{0, 0}
}

type StoreAnswer struct {
	Answer               StoreAnswerStoreAnswer `protobuf:"varint,1,opt,name=answer,proto3,enum=protocol.StoreAnswerStoreAnswer" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StoreAnswer) Reset()         { *m = StoreAnswer{} }
func (m *StoreAnswer) String() string { return proto.CompactTextString(m) }
func (*StoreAnswer) ProtoMessage()    {}
func (*StoreAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33ff9908270bf1e, []int{0}
}

func (m *StoreAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreAnswer.Unmarshal(m, b)
}
func (m *StoreAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreAnswer.Marshal(b, m, deterministic)
}
func (m *StoreAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreAnswer.Merge(m, src)
}
func (m *StoreAnswer) XXX_Size() int {
	return xxx_messageInfo_StoreAnswer.Size(m)
}
func (m *StoreAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_StoreAnswer proto.InternalMessageInfo

func (m *StoreAnswer) GetAnswer() StoreAnswerStoreAnswer {
	if m != nil {
		return m.Answer
	}
	return StoreAnswer_OK
}

func init() {
	proto.RegisterType((*StoreAnswer)(nil), "protocol.StoreAnswer")
	proto.RegisterEnum("protocol.StoreAnswerStoreAnswer", StoreAnswerStoreAnswer_name, StoreAnswerStoreAnswer_value)
}

func init() { proto.RegisterFile("STORE_ANSWER.proto", fileDescriptor_a33ff9908270bf1e) }

var fileDescriptor_a33ff9908270bf1e = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0x0e, 0xf1, 0x0f,
	0x72, 0x8d, 0x77, 0xf4, 0x0b, 0x0e, 0x77, 0x0d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x75, 0x5c, 0xdc, 0xc1, 0x25, 0xf9, 0x45, 0xa9, 0x8e, 0x79,
	0xc5, 0xe5, 0xa9, 0x45, 0x42, 0x96, 0x5c, 0x6c, 0x89, 0x60, 0x96, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x9f, 0x91, 0xa2, 0x1e, 0x4c, 0xa5, 0x1e, 0x92, 0x32, 0xbd, 0x62, 0x04, 0x3b, 0x08, 0xaa, 0x41,
	0xc9, 0x84, 0x8b, 0x1b, 0x49, 0x58, 0x88, 0x8d, 0x8b, 0xc9, 0xdf, 0x5b, 0x80, 0x41, 0x48, 0x88,
	0x8b, 0xcf, 0xd1, 0x27, 0xc8, 0xd5, 0xd1, 0x25, 0x32, 0x1e, 0xec, 0x10, 0x17, 0x01, 0x46, 0x21,
	0x4e, 0x2e, 0x56, 0xd7, 0xa0, 0x20, 0xff, 0x20, 0x01, 0xa6, 0x24, 0x36, 0xb0, 0xf9, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0x7c, 0xf6, 0x02, 0xa6, 0x00, 0x00, 0x00,
}
