// Code generated by protoc-gen-go. DO NOT EDIT.
// source: STORE_ANSWER.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreAnswer struct {
	StoredSuccesfuly     bool     `protobuf:"varint,1,opt,name=storedSuccesfuly,proto3" json:"storedSuccesfuly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreAnswer) Reset()         { *m = StoreAnswer{} }
func (m *StoreAnswer) String() string { return proto.CompactTextString(m) }
func (*StoreAnswer) ProtoMessage()    {}
func (*StoreAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33ff9908270bf1e, []int{0}
}

func (m *StoreAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreAnswer.Unmarshal(m, b)
}
func (m *StoreAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreAnswer.Marshal(b, m, deterministic)
}
func (m *StoreAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreAnswer.Merge(m, src)
}
func (m *StoreAnswer) XXX_Size() int {
	return xxx_messageInfo_StoreAnswer.Size(m)
}
func (m *StoreAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_StoreAnswer proto.InternalMessageInfo

func (m *StoreAnswer) GetStoredSuccesfuly() bool {
	if m != nil {
		return m.StoredSuccesfuly
	}
	return false
}

func init() {
	proto.RegisterType((*StoreAnswer)(nil), "protocol.StoreAnswer")
}

func init() { proto.RegisterFile("STORE_ANSWER.proto", fileDescriptor_a33ff9908270bf1e) }

var fileDescriptor_a33ff9908270bf1e = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0x0e, 0xf1, 0x0f,
	0x72, 0x8d, 0x77, 0xf4, 0x0b, 0x0e, 0x77, 0x0d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x96, 0x5c, 0xdc, 0xc1, 0x25, 0xf9, 0x45, 0xa9, 0x8e, 0x79,
	0xc5, 0xe5, 0xa9, 0x45, 0x42, 0x5a, 0x5c, 0x02, 0xc5, 0x20, 0x6e, 0x4a, 0x70, 0x69, 0x72, 0x72,
	0x6a, 0x71, 0x5a, 0x69, 0x4e, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x86, 0x78, 0x12,
	0x1b, 0xd8, 0x10, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xeb, 0x19, 0xd0, 0x61, 0x00,
	0x00, 0x00,
}
