// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UNPIN.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UnPin struct {
	FileHash             string   `protobuf:"bytes,1,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	PasswordHash         string   `protobuf:"bytes,2,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnPin) Reset()         { *m = UnPin{} }
func (m *UnPin) String() string { return proto.CompactTextString(m) }
func (*UnPin) ProtoMessage()    {}
func (*UnPin) Descriptor() ([]byte, []int) {
	return fileDescriptor_0641886338c70c7a, []int{0}
}

func (m *UnPin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnPin.Unmarshal(m, b)
}
func (m *UnPin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnPin.Marshal(b, m, deterministic)
}
func (m *UnPin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnPin.Merge(m, src)
}
func (m *UnPin) XXX_Size() int {
	return xxx_messageInfo_UnPin.Size(m)
}
func (m *UnPin) XXX_DiscardUnknown() {
	xxx_messageInfo_UnPin.DiscardUnknown(m)
}

var xxx_messageInfo_UnPin proto.InternalMessageInfo

func (m *UnPin) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *UnPin) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func init() {
	proto.RegisterType((*UnPin)(nil), "protocol.UnPin")
}

func init() { proto.RegisterFile("UNPIN.proto", fileDescriptor_0641886338c70c7a) }

var fileDescriptor_0641886338c70c7a = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0e, 0xf5, 0x0b, 0xf0,
	0xf4, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xee,
	0x5c, 0xac, 0xa1, 0x79, 0x01, 0x99, 0x79, 0x42, 0x52, 0x5c, 0x1c, 0x69, 0x99, 0x39, 0xa9, 0x1e,
	0x89, 0xc5, 0x19, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x90, 0x12, 0x17, 0x4f,
	0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x0a, 0x58, 0x9e, 0x09, 0x2c, 0x8f, 0x22, 0x96, 0xc4,
	0x06, 0x36, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xfc, 0xd0, 0xee, 0x68, 0x00, 0x00,
	0x00,
}
